TP_website/TP_app/urls.py
from django.contrib import admin
from django.urls import path
from . import views
app_name = 'TP_app'

urlpatterns = [
    path('', views.index, name= "index"),
    #Authentication
    path('register/', views.register_page, name= "register"),
    path('login/', views.login_request, name='login'),
    path('logout/', views.logout_request, name='logout'),

    path('TP_app/', views.register_student, name="register_student"),
    path('register_job/', views.register_job, name="register_job"),
    path('register_student_submit/', views.register_student_submit, name="register_student_submit"),
    path('register_job_submit/', views.register_job_submit, name="register_job_submit"),
    path('companies/', views.companies, name="companies"),
    path('upcoming_events/', views.upcoming_events, name="upcoming_events"),
    path('register_job_submit/', views.register_job_submit, name="register_job_submit"),
    path('add_company/', views.add_company, name="add_company"),
    path('add_company_submit/', views.add_company_submit, name="add_company_submit"),
    path('Statistics/', views.Statistics, name="Statistics"),
]

TP_website/TP_website/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('TP_app.urls')),
    path('', include("django.contrib.auth.urls")),
]

TP_website/TP_app/models.py
from django.db import models

# Create your models here.
class StudentInfo(models.Model):
    uname = models.CharField(max_length=200, default='')
    email = models.CharField(max_length=200)
    phoneno = models.CharField(max_length=200)
    event = models.CharField(max_length=20)

    def __str__(self):
        return self.uname
    
class JobInfo(models.Model):
    uname = models.CharField(max_length=200, default='')
    email = models.CharField(max_length=200)
    phoneno = models.CharField(max_length=200)
    college = models.CharField(max_length=200)
    graduation = models.CharField(max_length=200)
    company = models.CharField(max_length=200)
    profile = models.CharField(max_length=200)

    def __str__(self):
        return self.company
    
class EventInfo(models.Model):
    eventname = models.CharField(max_length=200)
    description = models.CharField(max_length=200)
    eventdate = models.CharField(max_length=200)

    def __str__(self):
        return self.eventname
    
class CompanyInfo(models.Model):
    cname = models.CharField(max_length=200)
    role = models.CharField(max_length=200)
    salary = models.CharField(max_length=200)

    def __str__(self):
        return self.cname

TP_website/TP_app/forms.py
from django import forms 
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from django.contrib.auth import login, authenticate

class RegisterForm(UserCreationForm):
    email = forms.EmailField()

    class Meta:
        model = User
        fields = ["username",'email',"password1","password2"]

TP_website/TP_app/views.py
from django.shortcuts import render,redirect
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from django.contrib.auth.models import User
from .forms import RegisterForm
from django.contrib import messages
from django.contrib.auth import login, logout, authenticate
from django.contrib.auth.decorators import login_required
from .models import StudentInfo, JobInfo, EventInfo, CompanyInfo

# Create your views here.
def index(request):
    return render(request, 'includes/index.html')

def register_page(request):
    if request.method == 'POST':
        form = RegisterForm(request.POST)
        if form.is_valid():
            form.save()
            messages.success(request, 'You are successfully registered.')
        return redirect('/')
    else:
        form = RegisterForm()

    return render(request, "registration/register.html", {"form":form})


def login_request(request):
    if request.method == "POST":
        form = AuthenticationForm(request, request.POST)
        if form.is_valid():
            username = form.cleaned_data.get("username")
            password = form.cleaned_data.get("password")
            user = authenticate(username=username, password=password)
            if user is not None:
                login(request, user)
                messages.info(request, f"You are now logged in as {username}.")
                return redirect("/")
            else:
                messages.error(request, "Invalid username or password")
        else:
            messages.error(request, "Invalid username or password")
    form = AuthenticationForm()
    return render(request, "registration/login.html",{"form":form})


def logout_request(request):
    logout(request)
    messages.info(request, "Logged out successfully!")
    return redirect("/")

@login_required(login_url='/login/')
def register_student(request):
    return render(request, 'TP_app/register_student.html')

def register_student_submit(request):
    print("Hello form is submitted")
    print(request.POST['name'])
    print(request.POST['event'])
    name = request.POST['name']
    email = request.POST['email']
    phoneno = request.POST['phoneno']
    event = request.POST['event']
    Student_Info = StudentInfo(uname=name,email=email,phoneno=phoneno, event=event)
    Student_Info.save()
    messages.success(request, 'You have successfully registered.')
    return render(request, 'TP_app/register_student.html')


def companies(request):
    return render(request, 'includes/company.html')

@login_required(login_url='/login/')
def register_job(request):
    return render(request, 'includes/register_job.html')

def register_job_submit(request):
    print("Hello form is submitted")
    print(request.POST['name'])
    print(request.POST['college'])
    print(request.POST['company'])
    print(request.POST['profile'])
    print(request.POST['graduation'])
    print(request.POST['phoneno'])
    name = request.POST['name']
    email = request.POST['email']
    phoneno = request.POST['phoneno']
    college = request.POST['college']
    graduation = request.POST['graduation']
    company = request.POST['company']
    profile = request.POST['profile']

    Job_Info = JobInfo(uname=name, email=email, phoneno=phoneno, college=college, graduation=graduation, company=company, profile=profile)
    Job_Info.save()
    messages.success(request, 'You have successfully registered.')
    return render(request, 'includes/register_job.html')

def upcoming_events(request):
    return render(request, 'includes/upcoming_events.html')

def upcoming_events_submit(request):
    print(request.POST['everyone'])
    eventname = request.POST['eventname']
    description = request.POST['description']
    eventdate = request.POST['eventdate']
    Event_Info = EventInfo(eventname=eventname,description=description,eventdate=eventdate)
    Event_Info.save()
    messages.success(request, 'Your Event is successfully saved.')
    return render(request, 'includes/upcoming_events.html')

def add_company(request):
    return render(request, 'includes/add_company.html')

def add_company_submit(request):
    print(request.POST['name'])
    cname = request.POST['cname']
    role = request.POST['role']
    salary = request.POST['salary']
    Company_Info = CompanyInfo(cname=cname,role=role,salary=salary)
    Company_Info.save()
    messages.success(request, 'You have successfully saved.')
    return render(request, 'includes/add_company.html')

def Statistics(request):
    return render(request, 'includes/statistics.html')


TP_website/TP_app/templates/TP_app/register_student.html
{% extends "includes/index.html" %}
{% include 'includes/messages.html' %}

{% load bulma_tags %}
{% load static %}
<link href="{% static '/css/styles.css' %}" rel="stylesheet">  
<title>{% block title%}Register Here{% endblock %}</title>
{% block content %}
<br>
<div class="tile is-ancestor">
    <div class="tile is-6 is-vertical is-parent">
      <div class="tile is-child box">
        <figure class="image is-4by3">
          <img src="{% static 'images/register_student.svg'%}" alt="Event 1">
      </figure>
      </div>
    </div>
    <div class="tile is-parent">
      <div class="tile is-child box">
        <p class="title">Register for event:</p>
        <form action="/register_student_submit/" method="POST">
          {% csrf_token %}
          
          <div class="field">
            <label class="label">Username</label>
            <div class="control has-icons-left has-icons-right">
              <input class="input " type="text" placeholder="Text input" value="{{user.username}}" name="name">
              <span class="icon is-small is-left">
                <i class="fas fa-user"></i>
              </span>
            </div>
          </div>
          <div class="field">
            <label class="label">Email id</label>
            <div class="control">
              <input class="input" type="email" placeholder="" name="email" value="{{user.email}}">
            </div>
          </div>
          <div class="field">
            <label class="label">Phone no</label>
            <div class="control">
              <input class="input" type="text" placeholder="" name="phoneno">
            </div>
          </div>
          <div class="field">
            <label for="" class="label">Events</label>
            <div class="control">
              <div class="select">
                <select name="event">
                  <option>Select Event</option>
                  <option>Machine Learning</option>
                  <option>Inplant Training</option>
                  <option>BlockChain</option>
                  <option>Augmented Reality</option>
                </select>
              </div>
            </div>
          </div>
            
            <button type="submit" class="button is-success is-light">Register</button>
        </form>
      </div>
    </div>
  </div>
{% endblock %}

TP_website/TP_app/templates/includes/Events_login.html
{% load static %}

<div class="tile is-ancestor mt-6">
    <div class="tile is-parent">
        <div class="tile is-child " id="events">
            {% if user.is_superuser %}
            <a href="{% url 'TP_app:upcoming_events' %}">
                <button class="button is-light is-outlined is-pulled-right"
                    style="background-color: rgba(105, 0, 255, 0.11);color: #6900FF;"><strong><i class="fa fa-plus-circle" aria-hidden="true"></i>  Add Events</strong></button>
            </a>

            {% endif %}
            <p class="title mx-4">UPCOMING EVENTS</p>
            <div class="tile is-ancestor">
                <div class="tile is-parent">
                    <article class="tile is-child ">
                        <div class="card mx-4">
                            <div class="card-image">
                                <figure class="image is-4by3">
                                    <img src="{% static 'images/inplant.png'%}" alt="Event 1">
                                </figure>
                            </div>
                            <div class="card-content">
                                <p class="title">Inplant Training</p>
                                <div class="content">
                                    This program discusses about DSA, mock tests for interviews and
                                    Aptitude.<a>@IT.io</a>. <br>
                                    <a href="/TP_app">
                                        <button class="button is-light is-outlined mt-3 is-pulled-right"
                                            style="background-color: rgba(105, 0, 255, 0.11);color: #6900FF;"><strong><i class="fa fa-user-plus" aria-hidden="true"></i>  Register</strong></button>
                                    </a>
                                    <br>
                                    <time datetime="2016-1-1">23 Sept 2023</time>
                                </div>
                            </div>
                        </div>
                    </article>
                </div>
                <div class="tile is-parent">
                    <article class="tile is-child ">
                        <div class="card mx-4">
                            <div class="card-image">
                                <figure class="image is-4by3">
                                    <img src="{% static 'images/ML.gif'%}" alt="Event 1">
                                </figure>
                            </div>
                            <div class="card-content">
                                <p class="title">Machine Learning</p>
                                <div class="content">
                                    One of the fastest and emerging technology by the top speakers in our panel.
                                    <a>@ML.io</a>. <br>
                                    <a href="/TP_app">
                                        <button class="button is-light is-outlined mt-3 is-pulled-right"
                                            style="background-color: rgba(105, 0, 255, 0.11);color: #6900FF;"><strong><i class="fa fa-user-plus" aria-hidden="true"></i>  Register</strong></button>
                                    </a>
                                    <br>
                                    <time datetime="2016-1-1">22 Sept 2023</time>
                                </div>
                            </div>
                        </div>
                    </article>
                </div>
                <div class="tile is-parent">
                    <article class="tile is-child ">
                        <div class="card mx-4">
                            <div class="card-image">
                                <figure class="image is-4by3">
                                    <img src="{% static 'images/BC.gif'%}" alt="Placeholder image">
                                </figure>
                            </div>
                            <div class="card-content">
                                <p class="title">BlockChain</p>
                                <div class="content">
                                    Want to know how the "crytographical transaction" is being done? Register here for
                                    some insightful knowledge<a>@BC.io</a> <br>
                                    <a href="/TP_app">
                                        <button class="button is-light is-outlined mt-3 is-pulled-right"
                                            style="background-color: rgba(105, 0, 255, 0.11);color: #6900FF;"><strong><i class="fa fa-user-plus" aria-hidden="true"></i>  Register</strong></button>
                                    </a>
                                    <br>
                                    <time datetime="2016-1-1">1 Oct 2023</time>
                                </div>
                            </div>
                        </div>
                    </article>
                </div>
                <div class="tile is-parent">
                    <article class="tile is-child ">
                        <div class="card mx-4">
                            <div class="card-image">
                                <figure class="image is-4by3">
                                    <img src="{% static 'images/VR.gif' %}" alt="Placeholder image">
                                </figure>
                            </div>
                            <div class="card-content">
                                <p class="title">AR</p>
                                <div class="content">
                                    Virtual reality/Augmented Reality appears to offer educational potentials. Click
                                    here for this amazing event. <a>@AR.io</a>. <br>
                                    <a href="/TP_app">
                                        <button class="button is-light is-outlined mt-3 is-pulled-right"
                                            style="background-color: rgba(105, 0, 255, 0.11);color: #6900FF;"><strong><i class="fa fa-user-plus" aria-hidden="true"></i>  Register</strong></button>
                                    </a>
                                    <br>
                                    <time datetime="2016-1-1">1 Dec 2023</time>
                                </div>
                            </div>
                        </div>
                    </article>
                </div>
            </div>

        </div>
    </div>
</div>

TP_website/TP_app/templates/includes/Events_not_login.html
{% load static %}
<div class="tile is-ancestor mt-6" id="events">
    <div class="tile is-parent">
        <div class="tile is-child ">
            <p class="title">UPCOMING EVENTS</p>
            <div class="tile is-ancestor">
                <div class="tile is-parent">
                    <article class="tile is-child ">
                        <div class="card mx-4">
                            <div class="card-image">
                                <figure class="image is-4by3">
                                    <img src="{% static 'images/inplant.png'%}" alt="Event 1">
                                </figure>
                            </div>
                            <div class="card-content">
                                <p class="title">Inplant Training</p>
                                <div class="content">
                                    This program discusses about DSA, mock tests for interviews and Aptitude.<a>@IT.io</a>. <br>
                                    <a href="/TP_app">
                                        <button class="button is-light is-outlined mt-3 is-pulled-right" style="background-color: rgba(105, 0, 255, 0.11);color: #6900FF;"><strong><i class="fa fa-user-plus" aria-hidden="true"></i>  Register</strong></button>
                                    </a> 
                                    <br>
                                    <time datetime="2016-1-1">23 Sept 2023</time>
                                </div>
                            </div>
                        </div>
                    </article>
                </div>
                <div class="tile is-parent">
                    <article class="tile is-child ">
                        <div class="card">
                            <div class="card-image">
                                <figure class="image is-4by3">
                                    <img src="{% static 'images/ML.gif'%}" alt="Event 1">
                                </figure>
                            </div>
                            <div class="card-content">
                                <p class="title">Machine Learning</p>
                                <div class="content">
                                    One of the fastest and emerging technology by the top speakers in our panel. <a>@ML.io</a>. <br>
                                    <a href="/TP_app">
                                        <button class="button is-light is-outlined mt-3 is-pulled-right" style="background-color: rgba(105, 0, 255, 0.11);color: #6900FF;"><strong><i class="fa fa-user-plus" aria-hidden="true"></i>  Register</strong></button>
                                    </a> 
                                    <br>
                                    <time datetime="2016-1-1">22 Sept 2023</time>
                                </div>
                            </div>
                        </div>
                    </article>
                </div>
                <div class="tile is-parent">
                    <article class="tile is-child ">
                        <div class="card">
                            <div class="card-image">
                                <figure class="image is-4by3">
                                    <img src="{% static 'images/BC.gif'%}" alt="Placeholder image">
                                </figure>
                            </div>
                            <div class="card-content">
                                <p class="title">BlockChain</p>
                                <div class="content">
                                    Want to know how the "crytographical  transaction" is being done?  Register  here for some more info. <a>@BC.io</a>. <br>
                                    <a href="/TP_app">
                                        <button class="button is-light is-outlined mt-3 is-pulled-right" style="background-color: rgba(105, 0, 255, 0.11);color: #6900FF;"><strong><i class="fa fa-user-plus" aria-hidden="true"></i>  Register</strong></button>
                                    </a> 
                                    <br>
                                    <time datetime="2016-1-1">1 Oct 2023</time>
                                </div>
                            </div>
                        </div>
                    </article>
                </div>
                <div class="tile is-parent">
                    <article class="tile is-child ">
                        <div class="card">
                            <div class="card-image">
                                <figure class="image is-4by3">
                                    <img src="{% static 'images/VR.gif' %}" alt="Placeholder image">
                                </figure>
                            </div>
                            <div class="card-content">
                                <p class="title">Augmented Reality</p>
                                <div class="content">
                                    Virtual reality/Augmented Reality appears to offer educational potentials.<a>@AR.io</a><br>
                                    <a href="/TP_app">
                                        <button class="button is-light is-outlined mt-3 is-pulled-right" style="background-color: rgba(105, 0, 255, 0.11);color: #6900FF;"><strong><i class="fa fa-user-plus" aria-hidden="true"></i>  Register</strong></button>
                                    </a> 
                                    <br>
                                    <time datetime="2016-1-1">1 Dec 2023</time>
                                </div>
                            </div>
                        </div>
                    </article>
                </div>
            </div>

        </div>
        
    </div>
    
</div>

TP_website/TP_app/templates/includes/messages.html
{% if messages %}
        {% for message in messages %}
            {% if message.tags == 'success'%}
                
                <div class="notification is-success is-light">
                    <button class="delete" onclick="this.parentElement.style.display='none'"></button>
                    <strong>{{message}}</strong>
                </div>
            {% elif message.tags == 'info'%}
                <div class="notification is-info is-light">
                    <button class="delete" onclick="this.parentElement.style.display='none'"></button>
                    <strong>{{message}}</strong>
                </div>
            {% elif message.tags == 'warning'%}
                <div class="notification is-warning is-light">
                    <button class="delete" onclick="this.parentElement.style.display='none'"></button>
                    <strong>{{message}}</strong>
                </div>
            {% elif message.tags == 'error'%}
                <div class="notification is-warning is-light">
                    <button class="delete" onclick="this.parentElement.style.display='none'"></button>
                    <strong>{{message}}</strong>
                </div>
            {% endif %}
        {% endfor %}
{% endif %}

TP_website/TP_app/templates/includes/navbar.html
<nav class="navbar" role="navigation" aria-label="main navigation">
    <div class="navbar-brand">
        <a class="navbar-item" href="">
            <img src="https://img.icons8.com/office/40/000000/code.png"/>
        </a>

        <a role="button" class="navbar-burger burger" aria-label="menu" aria-expanded="false" data-target="navbarBasicExample">
            <span aria-hidden="true"></span>
            <span aria-hidden="true"></span>
            <span aria-hidden="true"></span>
        </a>
    </div>

    <div id="navbarBasicExample" class="navbar-menu">
        <div class="navbar-start">
            <a class="navbar-item" href="/">
                <strong>Home</strong>
            </a>
            <a class="navbar-item" href="/#about" id="button">
                <strong>Objectives</strong>
            </a>
            <a class="navbar-item" href="/#events" id=button1>
                <strong>Events</strong>
            </a>
            <a class="navbar-item" href="{% url 'TP_app:Statistics'%}" >
                <strong>Stats</strong>
            </a>
            <a class="navbar-item" href="{% url 'TP_app:companies'%}" >
                <strong>Companies</strong>
            </a>
    
    </div>
            
        {% if user.is_authenticated %}
        <div class="navbar-end">
            <div class="navbar-item">
                <div class="buttons">
                    <a class="button is-primary is-light " href="/">
                    <strong><i class="fa fa-user" aria-hidden="true"></i> {{user.username}}</strong>
                    </a>
                    <a class="button is-danger is-light" href="{% url 'TP_app:logout'%}">
                        <strong>Log out</strong>
                    </a>
                </div>
            </div>
            {% else %}
            <div class="navbar-item">
                <div class="buttons">
                    <a class="button is-success is-light " href="{% url 'TP_app:register'%}">
                    <strong>Sign up</strong>
                    </a>
                    <a class="button is-light is-danger" href="{% url 'TP_app:login'%}">
                    <strong>Log in</strong>
                    </a>
                </div>
            </div>
        </div>
        
        {% endif %}
    </div>
</nav>

TP_website/TP_app/templates/includes/register_job.html
{% extends "includes/index.html" %}
{% include 'includes/messages.html' %}

{% load bulma_tags %}
{% load static %}
<link href="{% static '/css/styles.css' %}" rel="stylesheet">
<title>{% block title%}Register Here{% endblock %}</title>
{% block content %}
<br>
<div class="tile is-ancestor">
    <div class="tile is-6 is-vertical is-parent">
        <div class="tile is-child box">
            <figure class="image is-4by3">
                <img src="{% static 'images/attach.svg'%}" alt="Event 1">
            </figure>
        </div>
    </div>
    <div class="tile is-parent">
        <div class="tile is-child box">
            <p class="title">Apply for job:</p>
            <form action="{% url 'TP_app:register_job_submit'%}" method="POST">
                {% csrf_token %}
                <div class="field">
                    <label class="label">Username</label>
                    <div class="control has-icons-left has-icons-right">
                        <input class="input " type="text" placeholder="Text input" value="{{user.username}}"
                            name="name">
                        <span class="icon is-small is-left">
                            <i class="fas fa-user"></i>
                        </span>
                    </div>
                </div>
                <div class="field">
                    <label class="label">Email id</label>
                    <div class="control">
                        <input class="input" type="email" placeholder="" name="email" value="{{user.email}}">
                    </div>
                </div>

                <div class="field">
                    <label class="label">Phone no</label>
                    <div class="control">
                        <input class="input" type="text" placeholder="" name="phoneno">
                    </div>
                </div>
                <div class="field">
                    <label class="label">College</label>
                    <div class="control">
                        <input class="input" type="text" placeholder="" name="college">
                    </div>
                </div>
                <div class="field">
                    <label class="label">Graduation Year</label>
                    <div class="control">
                        <input class="input" type="text" placeholder="YYYY" name="graduation">
                    </div>
                </div>
                <div class="field">
                    <label for="" class="label">Company</label>
                    <div class="control">
                        <div class="select">
                            <select name="company">
                                <option>Select Company</option>
                                <option>Google</option>
                                <option>Amazon</option>
                                <option>IBM</option>
                                <option>Microsoft</option>
                                <option>Facebook</option>
                                <option>JPMC</option>
                                <option>Morgan Stanley</option>
                                <option>Goldman Sach's</option>
                                <option>Deutsche Bank</option>
                                <option>Quantiphi</option>
                                <option>Deloitte</option>
                                <option>Capgemini</option>
                            </select>
                        </div>
                    </div>
                </div>

                <div class="field">
                    <label class="label">Job Profile</label>
                    <div class="control">
                        <div class="select">
                            <select name="profile">
                                <option>Select Profile</option>
                                <option>SDE</option>
                                <option>Business Analyst</option>
                                <option>UI/UX designer</option>
                            </select>
                        </div>
                    </div>
                </div><br>
                <div class="file has-name">
                    <label class="file-label">
                        <input class="file-input" type="file" name="resume">
                        <span class="file-cta">
                            <span class="file-icon">
                                <i class="fas fa-upload"></i>
                            </span>
                            <span class="file-label">
                                Choose a file…
                            </span>
                        </span>
                        <span class="file-name">
                            Resume.pdf
                        </span>
                    </label>
                </div><br>
                <button type="submit" class="button is-success is-light"><strong>Register</strong></button>
            </form>
        </div>
    </div>
</div>
{% endblock %}